name: vivianwater
description: "A new Flutter project with WooCommerce integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  http: ^1.1.0
  provider: ^6.0.5
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1
  fluttertoast: ^8.2.12
  pin_code_fields: ^7.4.0
  # UI Components
  cached_network_image: ^3.2.3
  flutter_carousel_widget: ^2.1.2
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700